<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <BuildWithMSBuildOnMono>true</BuildWithMSBuildOnMono>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\SasthaLogo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\SasthaLogo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="modernhttpclient" Version="2.4.2" />
    <PackageReference Include="Plugin.BluetoothClassic" Version="1.1.5" />
    <PackageReference Include="Plugin.Permissions" Version="6.0.1" />
    <PackageReference Include="RestSharp" Version="110.2.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageReference Include="SQLiteNetExtensions" Version="2.1.0" />
    <PackageReference Include="Syncfusion.Licensing" Version="22.2.5" />
    <PackageReference Include="Syncfusion.Xamarin.Pdf" Version="22.2.5" />
    <PackageReference Include="Xam.Plugin.Connectivity" Version="3.2.0" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2578" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.7" />
    <PackageReference Include="CsvHelper" Version="30.0.1" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.1.0" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="2.0.6" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="companyPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="flyoutMenuPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="flyoutNavigation.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="homePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="machinePage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Report.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="startYarnTest.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="UserPage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="UserSearch.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="yarnCount.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="YCReport.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="YCSettings.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Java.Interop">
      <HintPath>..\..\..\..\..\dlls\Java.Interop_x86\Java.Interop.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Android">
      <HintPath>..\..\..\..\..\dlls\MONO.ANDROID_x86\MONO.ANDROID.DLL</HintPath>
    </Reference>
    <Reference Include="System.Data.Entity">
      <HintPath>..\..\..\..\..\..\..\..\Windows\Microsoft.NET\FrameworkArm64\v4.0.30319\System.Data.Entity.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>